#!/bin/bash

# =================================================================
# File:        audio_mod
# Author:      Charlie Martínez® <cmartinez@quirinux.org>
# License:     https://www.gnu.org/licenses/gpl-2.0.txt
# Purpose:     Variable module for package installation
# Distro:      Quirinux 2.x
# =================================================================

# Copyright (c) 2019-2025 Charlie Martínez. All Rights Reserved.  
# License: https://www.gnu.org/licenses/gpl-2.0.txt  
# Authorized and unauthorized uses of the Quirinux trademark:  
# See https://www.quirinux.org/aviso-legal  
#

# This variable module was created for Quirinux 2.0 and contains  
# necessary information for installing or uninstalling packages through
# "createmaster" program, which is used to build the master distribution.

#-----------------------------------------------------------------------

# MOD_NAME = Module name.
# MOD_PACKS = List of packages required by this module, separated by spaces.
# MOD_MEU =  Menu entry description for this module.

MOD_NAME="audio_mod"
MOD_PACKS="alsa-utils cheese cuetools clementine dir2ogg ffmpeg ffmpegthumbnailer flac flake gstreamer1.0-plugins-ugly gstreamer1.0-pulseaudio gstreamer1.0-alsa lame mencoder mpeg3-utils mpg123 mpg321 mplayer pavucontrol pavumeter sound-theme-freedesktop vlc vlc-plugin-svg vorbisgain vorbis-tools x264 x265 wav2cdr jq socat mpv pqiv"
MOD_MENU="Controladores básicos para sonido"
