#!/bin/bash

# =================================================================
# File:        files_mod
# Author:      Charlie Martínez® <cmartinez@quirinux.org>
# License:     https://www.gnu.org/licenses/gpl-2.0.txt
# Purpose:     Variable module for package installation
# Distro:      Quirinux 2.x
# =================================================================

# Copyright (c) 2019-2025 Charlie Martínez. All Rights Reserved.  
# License: https://www.gnu.org/licenses/gpl-2.0.txt  
# Authorized and unauthorized uses of the Quirinux trademark:  
# See https://www.quirinux.org/aviso-legal  
#

# This variable module was created for Quirinux 2.0 and contains  
# necessary information for installing or uninstalling packages through
# "createmaster" program, which is used to build the master distribution.

#-----------------------------------------------------------------------

# MOD_NAME = Module name.
# MOD_PACKS = List of packages required by this module, separated by spaces.
# MOD_MEU =  Menu entry description for this module.

MOD_NAME="files_mod"
MOD_PACKS="btrbk btrfs-compsize btrfs-heatmap btrfs-progs btrfsmaintenance dosfstools dmraid exfatprogs exfat-fuse f2fs-tools fatresize fatsort hfsutils hfsplus lvm2 mdadm nilfs-tools nfs-common ntfs-3g jfsutils reiserfsprogs reiser4progs sshfs xfsdump xfsprogs udisks2-btrfs udfclient udftools"
MOD_MENU="Controladores para sistemas de archivos"
